include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    deprecated_member_use: ignore
    no_leading_underscores_for_local_identifiers: ignore
    prefer_typing_uninitialized_variables: ignore
    unnecessary_null_comparison: ignore
    unused_field: ignore
    unused_local_variable: ignore
